name: Build Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify on success
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Build Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify on failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Build Failed! Check the latest commit.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
