name: health check

on:
  schedule:
    - cron: '15 8 12 6 * *'

jobs:
  health_check:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://www.jvrecords.fi
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false