name: Render
on: [push, pull_request]
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        if: ${{ github.event_name == 'push' }}
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-clhfe1mbbf9s73b0vs7g
          retries: 20
          wait: 16000
          sleep: 30000
